In [1]:
aList = ["Matthew", 24, "Mynzuw", True]

In [2]:
print(aList)

['Matthew', 24, 'Mynzuw', True]


In [46]:
Mahasiswa = ["Miftah Adha", "2021071008", "Informatika", "DAA", "14/9/2022", "Universtitas Pembangunan Jaya"]
print(Mahasiswa)

['Miftah Adha', '2021071008', 'Informatika', 'DAA', '14/9/2022', 'Universtitas Pembangunan Jaya']


In [39]:
bin_colors=["Red", "Green", "Blue", "Yellow"]
bin_colors[2]

'Blue'

In [29]:
Mahasiswa[1]

2021071008

In [32]:
Mahasiswa[5]

'Universtitas Pembangunan Jaya'

In [37]:
bin_colors[0:2]

['Red', 'Green']

In [62]:
Mahasiswa[1:3]

['2021071008', 'Informatika']

In [69]:
for aColor in bin_colors:
    print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [70]:
for aMhsw in Mahasiswa:
    print("UPJ " , aMhsw)

UPJ  Miftah Adha
UPJ  2021071008
UPJ  Informatika
UPJ  DAA
UPJ  14/9/2022
UPJ  Universtitas Pembangunan Jaya


In [71]:
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[1]

'Green'

In [73]:
bin_colors[2:]

('Blue', 'Yellow')

In [82]:
UPJ = ('Universitas','Pembangunan','Jaya')
UPJ[:3]

('Universitas', 'Pembangunan', 'Jaya')

In [87]:
nested_tuple = (100 , (200,400,600),300, (400,800))
print(nested_tuple)

(100, (200, 400, 600), 300, (400, 800))


In [94]:
bin_colors ={
"manual_color": "Yellow",
"approved_color": "Green",
"refused_color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [95]:
bin_colors.get('approved_color')

'Green'

In [91]:
bin_colors['approved_color']

'Green'

In [99]:
bin_colors['manual_color']="Cyan"
bin_colors['approved_color']="Magenta"
print(bin_colors)

{'manual_color': 'Cyan', 'approved_color': 'Magenta', 'refused_color': 'Red'}


In [100]:
data_diri ={
"Nama": "Miftah Adha",
"NIM": "2021071008",
"Prodi": "Informatika",
"Universitas" : "UPJ"
}
print(data_diri)

{'Nama': 'Miftah Adha', 'NIM': '2021071008', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [113]:
green = {'grass','leaves'}
print(green)

{'leaves', 'grass'}


In [114]:
green = {'grass','grass','leaves','leaves'}
print(green)

{'leaves', 'grass'}


In [128]:
red = {'rose', 'blood','leaves', 'fire hydrant'}
yellow = {'dandelions', 'leaves', 'fire hydrant'}

yellow|red

{'blood', 'dandelions', 'fire hydrant', 'leaves', 'rose'}

In [129]:
yellow&red

{'fire hydrant', 'leaves'}

In [130]:
import pandas as pd

In [141]:
df = pd.DataFrame([
['1', 'Fares', 32, True],
['2', 'Elena', 23, False],
['3', 'Steven', 40, True]])

In [142]:
df.columns = ['id', 'name', 'age', 'decision']

In [143]:
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [144]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [145]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [147]:
import numpy as np

In [148]:
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

In [149]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [150]:
print(type(myMatrix))


<class 'numpy.ndarray'>


In [151]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [152]:
print(type(myVector))

<class 'list'>


In [153]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [154]:
print(type(myVector))

<class 'numpy.ndarray'>


In [162]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [163]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

In [161]:
stack.pop()

'Yellow'

In [164]:
stack.isEmpty()

False